Improve File Handling in Kraken CSV
eprbell/dali-rp2 pull request #119
Opened 2023-02-11 00:11 UTC by macanudo527

This fixes some alternative market handling in the CCXT pair converter as well as allow the pair converter to continue with REST price resolution if the file isn't found on Google Drive.

2023-02-11 01:07 UTC, macanudo527 commented
I spoke too soon. I was only missing two other markets. We will most likely have to work out a better solution to just manually adding these though.

2023-02-11 05:25 UTC, eprbell commented
Sounds good, thanks for jumping on this!

2023-02-12 09:27 UTC, macanudo527 commented
This still results in the program self-terminating when pulling pricing for 6+ different crypto assets on my machine with 40gb a RAM. I will open another PR soon to better handle CSV caching.

2023-02-24 02:07 UTC, macanudo527 commented
Do you want to merge this PR for now, and then I can open another that splits up the CSVs since that will be a pretty big revision?

2023-02-24 03:44 UTC, eprbell commented
> Do you want to merge this PR for now, and then I can open another that splits up the CSVs since that will be a pretty big revision?

Ok, will review in the next couple of days.

2023-02-26 15:13 UTC, eprbell requested changes
LGTM: just a nit in a comment.

2023-02-26 15:13 UTC, eprbell commented on src/dali/plugin/pair_converter/ccxt.py
> +        # The exchange could have been added as an alt if so markets wouldn't have been built
as an alt: if so

2023-03-02 07:59 UTC, macanudo527 commented
This should be okay now. I have the chunking PR ready, just want to run it in the real-world and see if it holds up.

2023-03-02 15:12 UTC, eprbell approved these changes
LGTM

2023-03-05 00:49 UTC, merged