Fix Bitbank Typos and Missing fiat_ticker doc
eprbell/dali-rp2 pull request #130
Opened 2023-03-30 23:55 UTC by macanudo527

This is to address #128 as well as questions in the wiki about `fiat_ticker`.

2023-03-31 04:28 UTC, eprbell requested changes

2023-03-31 04:28 UTC, eprbell commented on docs/configuration_file.md
> +* `fiat_ticker` (optional): the 3 letter ISO code of the fiat currency being used;
Let's add a hyperlink to the ISO 4217 Wikipedia page (same thing below):
```suggestion
* `fiat_ticker` (optional): the 3 letter [ISO 4217 code](https://en.wikipedia.org/wiki/ISO_4217#List_of_ISO_4217_currency_codes) of the fiat currency being used;
```

2023-04-01 00:07 UTC, macanudo527 commented
Thanks for the suggestion! I'm sure that will be helpful to users.

2023-04-01 00:50 UTC, eprbell requested changes

2023-04-01 00:50 UTC, eprbell commented on docs/configuration_file.md
> +* `fiat_ticker` (optional): the 3 letter ISO code of the fiat currency being used;
Let's add the link here too.

2023-04-01 00:50 UTC, eprbell commented on docs/configuration_file.md
> +* `fiat_ticker` (optional): the 3 letter ISO code of the fiat currency being used;
And here.

2023-04-05 02:13 UTC, macanudo527 commented
This should be ok now.

2023-04-05 02:49 UTC, eprbell approved these changes
LGTM

2023-04-05 02:49 UTC, merged