Adding  a few more alt exhchange path/pairs to ccxt
eprbell/dali-rp2 pull request #185
Opened 2023-05-28 20:27 UTC by topherbuckley

2023-06-01 00:11 UTC, macanudo527 requested changes
Just some nits.

2023-06-01 00:11 UTC, macanudo527 commented on src/dali/plugin/pair_converter/ccxt.py
> +_OKEX: str = "Okex"
Could you put these in alphabetical order?

2023-06-01 00:11 UTC, macanudo527 commented on src/dali/plugin/pair_converter/ccxt.py
> +_EXCHANGE_DICT: Dict[str, Any] = {_BINANCE: binance, _BINANCEUS: binanceus, _COINBASE_PRO: coinbasepro, _GATE: gateio, _HUOBI: huobi, _KRAKEN: kraken, _UPBIT: upbit, _COINBASE: coinbase, _OKEX: okex}
Same here. Could you put these in alphabetical order?

2023-06-01 19:33 UTC, topherbuckley commented
> Just some nits.
> 
> And could you address the pylint error?

I fixed the line too long error via black, but there was also this error at the bottom of the report:
>src/dali/plugin/pair_converter/ccxt.py:90:0: C0301: Line too long (199/160) (line-too-long)

Not sure if this will show up again or not, but the closest thing I found was [this closed issue](https://github.com/pylint-dev/pylint/issues/4662) in the pylint dev repo, which says this issue was resolved. 

There was a mypy error that came after clearing the rest of the issues. I force pushed a rebase to take out the duplicate coinbase class def in the stub. That test just needs to be rerun (I ran it locally and it passed). 

The alphabetical ordering (in addition to the one in the imports that you didn't mention in your review) was also pushed. Let me know if you need anything else on this.

2023-06-05 02:48 UTC, macanudo527 approved these changes
Thanks for making the changes!

LGTM!

2023-06-05 02:48 UTC, merged