Fix/initialize markets
eprbell/dali-rp2 pull request #197
Opened 2023-08-13 19:43 UTC by alexeckert

Closes https://github.com/eprbell/dali-rp2/issues/161

2023-08-14 02:40 UTC, eprbell requested changes
Other than a typo and some test failures, this LGTM (but I don't have a Kraken account). @macanudo527, can you also review this?

2023-08-14 02:40 UTC, eprbell commented on src/dali/plugin/input/rest/kraken.py
> +                raise RP2RuntimeError("List of markets can't be converted to dictionary, since list does not contain exaxtly one market entry.")
Typo: exactly

2023-08-14 21:59 UTC, eprbell requested changes
There's still a static analysis failure.

2023-08-14 22:05 UTC, alexeckert commented
> There's still a static analysis failure.



> There's still a static analysis failure.

Yes, thanks the pylinted tests didn't like the name of the fixture. Ran pylint locally now, as it is not part of the pre-commit hook.

2023-08-15 00:09 UTC, eprbell commented
> > There's still a static analysis failure.
> 
> Yes, thanks the pylinted tests didn't like the name of the fixture. Ran pylint locally now, as it is not part of the pre-commit hook.

No worries. There's still some mypy errors. You can run mypy locally with `https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#development-workflow` and you can also run all the other CI test locally (see https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#development-workflow).

2023-09-05 23:54 UTC, macanudo527 commented
It seems like #198 addresses this more robustly. Is it all right to close this PR?

2023-09-06 02:17 UTC, eprbell commented
I tried to merge but there is one more small static analysis problem: once that's fixed this is good to go.

2023-09-06 17:37 UTC, alexeckert commented
@macanudo527 Sure thanks, still had to fix the typing issue any way.

2023-09-06 17:37 UTC, closed without merging