efactor find historical bars
eprbell/dali-rp2 pull request #270
Opened 2024-12-04 23:55 UTC by macanudo527

2025-01-08 23:31 UTC, macanudo527 commented
@eprbell Can you take a look at this when you get a chance?

2025-01-10 03:38 UTC, eprbell commented
> @eprbell Can you take a look at this when you get a chance?

Sure, I'll take a look in the weekend: could you fix the CI failure before that?

2025-01-13 04:20 UTC, eprbell requested changes
Looks good to me, after CI is fixed.

2025-01-13 04:20 UTC, eprbell commented on tests/test_abstract_ccxt_pair_converter.py
> +                timestamp=now_time,
Since this is a test wouldn't it be better to have fixed data (like 2023/1/1) rather than datetime.now()?

2025-01-14 07:43 UTC, macanudo527 commented on src/dali/abstract_ccxt_pair_converter_plugin.py
> +                if (datetime.now(timezone.utc) - cached_bundle[-1].timestamp).total_seconds() <= _TIME_GRANULARITY_STRING_TO_SECONDS[_ONE_WEEK]:
@eprbell I don't think I can use a set time for the example bars, because this guard clause checks for stale data by checking if the stamp is within the last week.

2025-01-14 07:44 UTC, macanudo527 commented on tests/test_abstract_ccxt_pair_converter.py
> +                timestamp=now_time,
I don't think I can since the guard clause checks for stale data. It needs to be a timestamp within the last week. See other comment.

2025-01-15 00:37 UTC, macanudo527 commented
@eprbell I had to downgrade `urllib3` due to an incompatibility with vcrpy 4.4 and python 3.10. I think we need to drop support for Python 3.8 and 3.9. I can do that in another PR.

2025-01-15 00:40 UTC, macanudo527 commented
@eprbell  I also removed the pandas stubs we wrote since there is a package that covers those now.

2025-01-16 04:49 UTC, eprbell commented
> @eprbell I had to downgrade `urllib3` due to an incompatibility with vcrpy 4.4 and python 3.10. I think we need to drop support for Python 3.8 and 3.9. I can do that in another PR.
> 
> If we drop support for 3.8/3.9 we can use the latest versions of vcrpy and urllib3.

Rather than downgrading libraries, I think we should change the supported Python to 3.10...3.13: no need to keep supporting old versions if they force us to use old dependencies.

2025-01-16 04:52 UTC, eprbell requested changes
LGTM: let's just update supported Python versions.

2025-01-16 04:52 UTC, eprbell commented on setup.cfg
> +    urllib3<2 # 2+ is incompatible with Python ~3.9
Let's instead support Python 3.10...3.13.

2025-01-16 07:46 UTC, macanudo527 commented on setup.cfg
> +    urllib3<2 # 2+ is incompatible with Python ~3.9
OK, should be good to go now. Thanks.

2025-01-20 18:30 UTC, eprbell approved these changes
LGTM

2025-01-21 00:04 UTC, merged