Coinbase historical data API expects UTC timestamps only.
eprbell/dali-rp2 pull request #31
Opened 2022-04-15 16:29 UTC by stevendavis

This is a small code change to force UTC timestamps when requesting historical data from Coinbase via the Historic_Crypto package.  The Coinbase API expects the from time stamp and to timestamp will be UTC timezone.

Unfortunately, the TestODSOutputDiff unit tests are failing. I may be mistaken, but I think the unit test expected results are incorrect and will need to be updated.

2022-04-15 20:58 UTC, eprbell commented
Do you have a pointer to the documentation mentioning that timezone should be UTC?

2022-04-15 21:46 UTC, stevendavis commented
The API is not thoroughly documented, but there is a discussion of timestamps and timezones on the forum here: https://forums.coinbasecloud.dev/t/invalid-end-on-product-candles-endpoint/320

2022-04-15 23:13 UTC, eprbell requested changes
Thanks for the reasearch, the link and the bug fix: good work! The ODS tests are failing because now the spot price for some transactions has changed. To fix that cp the failing files from output/ to input/golden.

2022-04-15 23:13 UTC, eprbell commented on src/dali/transaction_resolver.py
> +            transaction_utc_timestamp = transaction.timestamp_value.astimezone(timezone.utc)  # Coinbase API expects UTC timestamps only
Could you add the link you found (https://forums.coinbasecloud.dev/t/invalid-end-on-product-candles-endpoint/320) on this in the comment?

2022-04-16 02:24 UTC, eprbell commented
This looks good. Just update the files in input/golden and I'll approve: 
```
cp output/test_ods_output_diff/*.ods input/golden/
```

2022-04-16 16:21 UTC, eprbell approved these changes
Ship it!

2022-04-16 16:21 UTC, merged