Add exchange_withdrawal transaction type
eprbell/dali-rp2 pull request #35
Opened 2022-04-16 19:46 UTC by nitrocode

Potentially closes https://github.com/eprbell/dali-rp2/issues/33

2022-04-17 06:11 UTC, eprbell requested changes
Looks good to me, thanks for fixing! Just revert version-related changes and I'll approve.

2022-04-17 21:25 UTC, nitrocode commented
@eprbell thanks for the review but there still seems to be one more issue, no ? What do you think of the above description ? or do you think the `UNKNOWN` values in the 2nd related `send` type transaction is fine ?

2022-04-18 05:11 UTC, eprbell commented
Thanks for the details: will take a look at it tomorrow.

2022-04-18 17:01 UTC, eprbell commented
Oh, sorry, I may have missed your other comments. The `Sent Ethereum to Ethereum address` transaction of type `send` with 0 fee means that you sent some ETH to an external wallet. As such it is captured as an intra-transacation, however Coinbase doesn't know the destination so the plugin fills in the destination fields with __UNKNOWN. This is called an unresolved transaction: to learn more about this and how to fix unresolved transaction read https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#manual-section-csv. I should probably add a FAQ about this. Let me know if this answers your questions.

2022-04-18 18:41 UTC, eprbell commented
Added a FAQ about this: https://github.com/eprbell/dali-rp2/blob/main/docs/user_faq.md#what-if-a-transaction-is-generated-with-some-fields-set-to-__unknown

2022-04-19 05:14 UTC, eprbell approved these changes
Looks good.

2022-04-19 05:17 UTC, merged