Use keywords instead of strings in coinbase plugin
eprbell/dali-rp2 pull request #71
Opened 2022-08-07 11:53 UTC by iloveitaly

2022-08-07 22:15 UTC, eprbell commented
The test needs to be fixed: make the type string lowercase before checking its value.

2022-08-13 15:08 UTC, iloveitaly commented
@eprbell test should be fixed (passing locally).

2022-08-16 18:29 UTC, eprbell requested changes
I commented a while ago, but didn't submit the review... my bad.

2022-08-20 21:57 UTC, iloveitaly commented on src/dali/plugin/input/rest/coinbase.py
> +                            transaction_type=Keyword.SELL.name,
@eprbell Looks like got to this first in fb4f5a7! Let me know if you need anything else here.

2022-08-20 22:04 UTC, eprbell commented on src/dali/plugin/input/rest/coinbase.py
> +                            transaction_type=Keyword.SELL.name,
I did :-) Could you just undo changes to tests/test_plugin_coinbase.py? Then this can be merged.

2022-08-20 22:45 UTC, iloveitaly commented on src/dali/plugin/input/rest/coinbase.py
> +                            transaction_type=Keyword.SELL.name,
@eprbell done!

2022-08-20 22:54 UTC, eprbell approved these changes
LGTM!

2022-08-20 22:54 UTC, merged