Throw an exception when a manual csv does not have enough columns
eprbell/dali-rp2 pull request #74
Opened 2022-08-13 16:08 UTC by iloveitaly

I interpretted the "optional" columns to be optional within the CSV structure. This change
provides clear feedback to users if they do not include enough columns.

2022-08-13 18:40 UTC, eprbell requested changes

2022-08-13 18:40 UTC, eprbell commented on src/dali/plugin/input/csv/manual.py
> +                        raise ValueError("Not enough columns, the CSV must contain all columns, even optional columns.")
Nice! Can you add the same logic to out and intra?

2022-08-13 18:40 UTC, eprbell commented on src/dali/plugin/input/csv/manual.py
> +                        raise ValueError("Not enough columns, the CSV must contain all columns, even optional columns.")
Also let's tell users how many columns are needed:
```suggestion
                        raise ValueError(f"Not enough columns: the CSV must contain {self.__IN_NOTES_INDEX} columns.")
```

2022-08-13 21:13 UTC, iloveitaly commented
[Does this line](https://github.com/iloveitaly/dali-rp2/blob/da643f9dc08a19451aaae20dcf742fdea6049683/src/dali/transaction_resolver.py#L634) trigger your memory?

Maybe explicitly defining a fee as zero ensures that the sent amount is accurate. Ensures a level of correctness about the out flow which in doesn't need since the net amount settled to an account is net of fees?

2022-08-13 21:19 UTC, iloveitaly commented
@eprbell done! :)

2022-08-13 23:13 UTC, eprbell requested changes

2022-08-13 23:13 UTC, eprbell commented on src/dali/plugin/input/csv/manual.py
> +                        raise ValueError(f"Not enough columns: the CSV must contain {self.__IN_NOTES_INDEX} columns.")
```suggestion
                        raise ValueError(f"Not enough columns: the {self.__in_csv_file} CSV must contain {self.__IN_NOTES_INDEX} columns.")
```

2022-08-14 17:06 UTC, eprbell approved these changes
LGTM!

2022-08-14 17:09 UTC, merged