Add documents for CCXT, Bitbank, and Coincheck
eprbell/dali-rp2 pull request #90
Opened 2022-09-30 00:04 UTC by macanudo527

I just need to add documentation for the Pionex plugin. I seemed to overlook that.

2022-09-30 00:27 UTC, macanudo527 commented
The failed tests are caused by links to unmerged files in PR #80

2022-10-07 05:08 UTC, eprbell requested changes
Minor changes needed.

2022-10-07 05:08 UTC, eprbell commented on docs/configuration_file.md
>  * **[Data Loader Plugin Sections](#data-loader-plugin-sections)**
Add Coincheck and Pionex to the table of contents.

2022-10-11 02:02 UTC, macanudo527 commented
This should be wrapped up.

2022-10-11 18:31 UTC, eprbell requested changes
A conflict needs to be resolved.

2022-10-11 18:31 UTC, eprbell commented on docs/configuration_file.md
> +<<<<<<< Updated upstream
The section marked by `<<<<<<<`... `>>>>>>>` is a Git conflict and needs to be resolved manually.

2022-10-12 23:25 UTC, macanudo527 commented
Fixed the conflict.

2022-10-13 10:02 UTC, eprbell approved these changes
LGTM

2022-10-13 10:02 UTC, merged